crawl_settings:
  # Web crawler configuration (creaw4ai)
  start_url: "https://page.example.de/"
  max_urls_to_visit: 5
  check_content_changed: true # Check if content has changed before re-indexing
  target_elements: # Optional, specify which HTML elements to extract
    - "main"
    - "div#content"
  allowed_domains:
    - "example.de"
    - "another-example.de"
  exclude_domains:
    - "example.de/intranet"
    - "another-example.de/intranet"



milvus:
  # Milvus vector database configuration
  host: "milvus" # Useful for Docker or Kubernetes deployments. User docker compose service name (Usually "milvus" or "standalone")
  uri : "http://my_milvus_server:19530"   # "http://localhost:19530" 
  token: "root:Milvus"  # Optional authentication token
  collection_name: "documents"
  collection_description: "A collection of PDF documents"
  enable_dynamic_field: false
  auto_id: false

embedding:
  # Text embedding configuration
  type: "FastEmbed" # Ollam or FastEmbed
  connection_settings: {
    model_name: "intfloat/multilingual-e5-large",
 
  }
  chunk_overlap: 50 # Overlap between chunks for better context
  chunk_size: 1900 # Size of each chunk to be embedded, adjust based on model capabilities


  # embedding:
  # # Text embedding configuration
  # type: "Ollama"
  # connection_settings: {
  #   model_name: "nomic-embed-text",
  #   base_url : "https://my_ollama.de",
  #   headers: {
  #     "Authorization": "Bearer YOUR_API_KEY"
  #   }
  # }

